export const USERS_CREATE_REQUEST = 'USERS_CREATE_REQUEST';
export const USERS_CREATE_RECEIVE_SUCCESS = 'USERS_CREATE_RECEIVE_SUCCESS';
export const USERS_CREATE_RECEIVE_ERROR = 'USERS_CREATE_RECEIVE_ERROR';

export const USERS_READ_REQUEST = 'USERS_READ_REQUEST';
export const USERS_READ_RECEIVE_SUCCESS = 'USERS_READ_RECEIVE_SUCCESS';
export const USER_READ_RECEIVE_SUCCESS = 'USER_READ_RECEIVE_SUCCESS';
export const USERS_READ_RECEIVE_ERROR = 'USERS_READ_RECEIVE_ERROR';

export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST';
export const USERS_UPDATE_RECEIVE_SUCCESS = 'USERS_UPDATE_RECEIVE_SUCCESS';
export const USERS_UPDATE_RECEIVE_ERROR = 'USERS_UPDATE_RECEIVE_ERROR';

export const USERS_DELETE_REQUEST = 'USERS_DELETE';
export const USERS_DELETE_RECEIVE_SUCCESS = 'USERS_DELETE_RECEIVE_SUCCESS';
export const USERS_DELETE_RECEIVE_ERROR = 'USERS_DELETE_RECEIVE_ERROR';

export const USER_CHOOSE = 'USER_CHOOSE';
export const USER_CREATE = 'USER_CREATE';
